# Generated by Django 6.0 on 2026-01-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_subcategory_unique_together_category_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
